version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
        # auth:
        #   username: $DOCKER_HUB_USER_ID  # can specify string literal values
        #   password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
      - deploy:
          name: Push application Docker image
              # Esta sección nos permitirá saber que rama(s) activarán la instrucción de despliegue
              #branch: [circle_ci_publish, master]
              # Lo primerp que se hace en está sección, es hacer login con nuestras credenciales de dockerhub
              # el signo $ hace referencia a nuestras variables de entorno que configuramos en CircleCI
              # el nombre dockerapp_dockerapp es generado a través del comando docker compose run,
              # este construye la imagen con el prefijo(nombre) predeterminado del directorio actual
              # la primera dockerapp es el nombre de nuestro directorio actual
              # el segundo dockerapp es el nombre del servicio que definimos en nuestro archivo docker-compose.yml
          command: |
              docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
              docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
              docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
              docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
              docker push $DOCKER_HUB_USER_ID/dockerapp:latest
